spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password:
    url: jdbc:mysql://vegan.cqcvpkpizdej.ap-northeast-2.rds.amazonaws.com:3306/vegan?serverTimezone=Asia/Seoul
    username: root
  jpa:
    hibernate:
       ddl-auto: update
    properties:
       hibernate:
          format_sql: true
          show_sql: true
  security:
      oauth2:
        client:
          registration:
            google:
              client-id:
              client-secret:
              scope:
                - profile
                - email
  cloud:
    aws:
      credentials:
        accessKey:
        secretKey:
      s3:
        bucket: vegan-bucket
      region:
        static: ap-northeast-2
      stack:
        auto: false