auth:
  jwt:
   secret: ${JWT_SECRET_KEY:}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
  jpa:
    generate-ddl: false
    show-sql: false
  security:
      oauth2:
        client:
          registration:
            google:
              client-id: <your id>
              client-secret: your secret>
              scope:
                - profile
                - email