spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 10210305
    url: jdbc:mysql://localhost:3306/vegan?serverTimezone=Asia/Seoul
    username: root
  jpa:
    hibernate:
       ddl-auto: create-drop
    properties:
       hibernate:
          format_sql: true
          show_sql: true
  security:
      oauth2:
        client:
          registration:
            google:
              client-id: 855848506200-i0dr7hsjueqfj14d6bdmdgg9btuolu0p.apps.googleusercontent.com
              client-secret: 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
              scope:
                - profile
                - email